name: Waka README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "30 0,12 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "14"
  #     # - name: Install dependencies
  #     #   run: |
  #     #     npm ci
  #     - name: Update README
  #       run: |-
  #         # npm start
  #         cat README.md
  #     - name: Commit and push if changed
  #       run: |-
  #         git add .
  #         git diff
  #         git config --global user.email "github-action-bot@example.com"
  #         git config --global user.name "GitHub Action Bot"
  #         git commit -m "Updated README" -a || echo "No changes to commit"
  #         git push
